<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* wdn/templates_5.3/scss/pre.tmp.scss */
class __TwigTemplate_0af9c4b8a3780f3ebb705e971c4dd5c8 extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_5a27a8ba21ca79b61932376b2fa922d2 = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_5a27a8ba21ca79b61932376b2fa922d2->enter($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "wdn/templates_5.3/scss/pre.tmp.scss"));

        $__internal_6f47bbe9983af81f1e7450e9a3e3768f = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_6f47bbe9983af81f1e7450e9a3e3768f->enter($__internal_6f47bbe9983af81f1e7450e9a3e3768f_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "wdn/templates_5.3/scss/pre.tmp.scss"));

        // line 1
        echo "// This file is generated by sass-globber.
// Do not edit this file manually!
// Just add your styles/imports to your source file: pre.scss.

//////
// PRE
//////


// Variables
@import \"../../../node_modules/dcf/scss/variables/_variables.tmp-defaults\";
@import \"variables/_variables.abbreviations\";
@import \"variables/_variables.anchors\";
@import \"variables/_variables.angles\";
@import \"variables/_variables.animation\";
@import \"variables/_variables.app\";
@import \"variables/_variables.backgrounds\";
@import \"variables/_variables.badges\";
@import \"variables/_variables.blockquotes\";
@import \"variables/_variables.body\";
@import \"variables/_variables.borders\";
@import \"variables/_variables.breadcrumbs\";
@import \"variables/_variables.breakpoints\";
@import \"variables/_variables.button-groups\";
@import \"variables/_variables.buttons\";
@import \"variables/_variables.cards\";
@import \"variables/_variables.code\";
@import \"variables/_variables.color-palette\";
@import \"variables/_variables.colors-text\";
@import \"variables/_variables.datepickers\";
@import \"variables/_variables.details-summary\";
@import \"variables/_variables.figures\";
@import \"variables/_variables.focus\";
@import \"variables/_variables.forms-checkboxes-radios\";
@import \"variables/_variables.forms-selects\";
@import \"variables/_variables.forms\";
@import \"variables/_variables.headings\";
@import \"variables/_variables.input-groups\";
@import \"variables/_variables.lists\";
@import \"variables/_variables.marks\";
@import \"variables/_variables.modals\";
@import \"variables/_variables.modular-scale\";
@import \"variables/_variables.navigation\";
@import \"variables/_variables.notices\";
@import \"variables/_variables.paragraphs\";
@import \"variables/_variables.sizing\";
@import \"variables/_variables.slideshows\";
@import \"variables/_variables.sup-sub\";
@import \"variables/_variables.tables\";
@import \"variables/_variables.tabs\";
@import \"variables/_variables.transitions\";
@import \"variables/_variables.z-index\";


// Mixins
@import \"../../../node_modules/dcf/scss/mixins/_mixins.aspect-ratios\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.backgrounds\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.border-color\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.border-radius\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.border-style\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.border-width\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.box-alignment\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.colors\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.css-columns\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.display\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.flexbox\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.floats\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.grid\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.height-width\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.margins\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.media-queries\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.object-fit\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.object-position\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.opacity\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.order\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.overflow\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.padding\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.pointer-events\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.position\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.svg\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.tables\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.typography\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.visibility\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.z-index\";
@import \"mixins/_mixins.background-colors\";
@import \"mixins/_mixins.background-images\";
@import \"mixins/_mixins.blend-modes\";
@import \"mixins/_mixins.border-color\";
@import \"mixins/_mixins.colors\";
@import \"mixins/_mixins.filters\";
@import \"mixins/_mixins.fonts\";
@import \"mixins/_mixins.typography\";


// Functions
@import \"../../../node_modules/dcf/scss/functions/_functions.encode-color\";
@import \"../../../node_modules/dcf/scss/functions/_functions.media-queries\";
@import \"../../../node_modules/dcf/scss/functions/_functions.to-number\";
";
        
        $__internal_5a27a8ba21ca79b61932376b2fa922d2->leave($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof);

        
        $__internal_6f47bbe9983af81f1e7450e9a3e3768f->leave($__internal_6f47bbe9983af81f1e7450e9a3e3768f_prof);

    }

    public function getTemplateName()
    {
        return "wdn/templates_5.3/scss/pre.tmp.scss";
    }

    public function getDebugInfo()
    {
        return array (  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("// This file is generated by sass-globber.
// Do not edit this file manually!
// Just add your styles/imports to your source file: pre.scss.

//////
// PRE
//////


// Variables
@import \"../../../node_modules/dcf/scss/variables/_variables.tmp-defaults\";
@import \"variables/_variables.abbreviations\";
@import \"variables/_variables.anchors\";
@import \"variables/_variables.angles\";
@import \"variables/_variables.animation\";
@import \"variables/_variables.app\";
@import \"variables/_variables.backgrounds\";
@import \"variables/_variables.badges\";
@import \"variables/_variables.blockquotes\";
@import \"variables/_variables.body\";
@import \"variables/_variables.borders\";
@import \"variables/_variables.breadcrumbs\";
@import \"variables/_variables.breakpoints\";
@import \"variables/_variables.button-groups\";
@import \"variables/_variables.buttons\";
@import \"variables/_variables.cards\";
@import \"variables/_variables.code\";
@import \"variables/_variables.color-palette\";
@import \"variables/_variables.colors-text\";
@import \"variables/_variables.datepickers\";
@import \"variables/_variables.details-summary\";
@import \"variables/_variables.figures\";
@import \"variables/_variables.focus\";
@import \"variables/_variables.forms-checkboxes-radios\";
@import \"variables/_variables.forms-selects\";
@import \"variables/_variables.forms\";
@import \"variables/_variables.headings\";
@import \"variables/_variables.input-groups\";
@import \"variables/_variables.lists\";
@import \"variables/_variables.marks\";
@import \"variables/_variables.modals\";
@import \"variables/_variables.modular-scale\";
@import \"variables/_variables.navigation\";
@import \"variables/_variables.notices\";
@import \"variables/_variables.paragraphs\";
@import \"variables/_variables.sizing\";
@import \"variables/_variables.slideshows\";
@import \"variables/_variables.sup-sub\";
@import \"variables/_variables.tables\";
@import \"variables/_variables.tabs\";
@import \"variables/_variables.transitions\";
@import \"variables/_variables.z-index\";


// Mixins
@import \"../../../node_modules/dcf/scss/mixins/_mixins.aspect-ratios\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.backgrounds\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.border-color\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.border-radius\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.border-style\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.border-width\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.box-alignment\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.colors\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.css-columns\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.display\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.flexbox\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.floats\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.grid\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.height-width\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.margins\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.media-queries\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.object-fit\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.object-position\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.opacity\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.order\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.overflow\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.padding\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.pointer-events\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.position\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.svg\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.tables\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.typography\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.visibility\";
@import \"../../../node_modules/dcf/scss/mixins/_mixins.z-index\";
@import \"mixins/_mixins.background-colors\";
@import \"mixins/_mixins.background-images\";
@import \"mixins/_mixins.blend-modes\";
@import \"mixins/_mixins.border-color\";
@import \"mixins/_mixins.colors\";
@import \"mixins/_mixins.filters\";
@import \"mixins/_mixins.fonts\";
@import \"mixins/_mixins.typography\";


// Functions
@import \"../../../node_modules/dcf/scss/functions/_functions.encode-color\";
@import \"../../../node_modules/dcf/scss/functions/_functions.media-queries\";
@import \"../../../node_modules/dcf/scss/functions/_functions.to-number\";
", "wdn/templates_5.3/scss/pre.tmp.scss", "/Users/abhirijal/unl_lockup_factory/templates/wdn/templates_5.3/scss/pre.tmp.scss");
    }
}
