<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFhQNDqI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFhQNDqI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFhQNDqI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFhQNDqI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFhQNDqI\App_KernelDevDebugContainer([
    'container.build_hash' => 'FhQNDqI',
    'container.build_id' => '574dfffc',
    'container.build_time' => 1649271937,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFhQNDqI');
