<?php

namespace ContainerMXzsuAx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SiC620SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SiC620S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SiC620S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IndexController::addLockup' => ['privates', '.service_locator.Pneh43o', 'get_ServiceLocator_Pneh43oService', true],
            'App\\Controller\\IndexController::deleteLockups' => ['privates', '.service_locator.whZT_KH', 'get_ServiceLocator_WhZTKHService', true],
            'App\\Controller\\IndexController::homePage' => ['privates', '.service_locator.whZT_KH', 'get_ServiceLocator_WhZTKHService', true],
            'App\\Controller\\IndexController::logout' => ['privates', '.service_locator.ris3J8l', 'get_ServiceLocator_Ris3J8lService', true],
            'App\\Controller\\IndexController::manageLockups' => ['privates', '.service_locator.whZT_KH', 'get_ServiceLocator_WhZTKHService', true],
            'App\\Controller\\IndexController::previewLockups' => ['privates', '.service_locator.whZT_KH', 'get_ServiceLocator_WhZTKHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\IndexController:addLockup' => ['privates', '.service_locator.Pneh43o', 'get_ServiceLocator_Pneh43oService', true],
            'App\\Controller\\IndexController:deleteLockups' => ['privates', '.service_locator.whZT_KH', 'get_ServiceLocator_WhZTKHService', true],
            'App\\Controller\\IndexController:homePage' => ['privates', '.service_locator.whZT_KH', 'get_ServiceLocator_WhZTKHService', true],
            'App\\Controller\\IndexController:logout' => ['privates', '.service_locator.ris3J8l', 'get_ServiceLocator_Ris3J8lService', true],
            'App\\Controller\\IndexController:manageLockups' => ['privates', '.service_locator.whZT_KH', 'get_ServiceLocator_WhZTKHService', true],
            'App\\Controller\\IndexController:previewLockups' => ['privates', '.service_locator.whZT_KH', 'get_ServiceLocator_WhZTKHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\IndexController::addLockup' => '?',
            'App\\Controller\\IndexController::deleteLockups' => '?',
            'App\\Controller\\IndexController::homePage' => '?',
            'App\\Controller\\IndexController::logout' => '?',
            'App\\Controller\\IndexController::manageLockups' => '?',
            'App\\Controller\\IndexController::previewLockups' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\IndexController:addLockup' => '?',
            'App\\Controller\\IndexController:deleteLockups' => '?',
            'App\\Controller\\IndexController:homePage' => '?',
            'App\\Controller\\IndexController:logout' => '?',
            'App\\Controller\\IndexController:manageLockups' => '?',
            'App\\Controller\\IndexController:previewLockups' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
