<?php

namespace ContainerMXzsuAx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLockupsGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\LockupsGenerator' shared autowired service.
     *
     * @return \App\Service\LockupsGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/LockupsGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SvgGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Service/LockupsConverter.php';

        $a = ($container->services['doctrine'] ?? $container->getDoctrineService());

        return $container->privates['App\\Service\\LockupsGenerator'] = new \App\Service\LockupsGenerator(new \App\Service\SvgGenerator(), $a, new \App\Service\LockupsConverter($a, ($container->services['kernel'] ?? $container->get('kernel', 1))));
    }
}
